version: "3.8"

services:
  game-server:
    build: .
    ports:
      - "${BIND_IP:-127.0.0.1}:5500:5500"
    environment:
      - NODE_ENV=production
      - PORT=5500
    restart: unless-stopped
    networks:
      - game-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - game-network
    depends_on:
      - game-server

networks:
  game-network:
    driver: bridge
