version: "3.8"

services:
  # Development server (mimics Render deployment)
  # Usage: docker-compose up dev
  dev:
    build: .
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production
      - PORT=5500
    volumes:
      # Mount source code for live development (optional - comment out for pure Render-like behavior)
      - ./public:/app/public:ro
      - ./server.js:/app/server.js:ro
      - ./package.json:/app/package.json:ro
    command: node server.js
    restart: unless-stopped

  # Production server with cloudflared tunnel
  # Usage: docker-compose up production
  production:
    build: .
    ports:
      - "${BIND_IP:-127.0.0.1}:5500:5500"
    environment:
      - NODE_ENV=production
      - PORT=5500
    restart: unless-stopped
    networks:
      - game-network
    profiles:
      - production

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - game-network
    depends_on:
      - production
    profiles:
      - production

networks:
  game-network:
    driver: bridge
