services:
  - type: web
    name: vibematch-arena
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5500
      - key: NODE_ENV
        value: production
