name: Deploy via Webhook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger deployment webhook
        run: |
          curl -X POST https://vibematch-arena.brad-dougherty.com/api/deploy \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: sha256=$(echo -n '${{ toJson(github) }}' | openssl dgst -sha256 -hmac '${{ secrets.WEBHOOK_SECRET }}' | awk '{print $2}')" \
            -d '{
              "ref": "${{ github.ref }}",
              "repository": {
                "full_name": "${{ github.repository }}"
              },
              "pusher": {
                "name": "${{ github.actor }}"
              },
              "head_commit": {
                "message": "${{ github.event.head_commit.message }}"
              }
            }'

      - name: Wait for server restart
        run: |
          echo "⏳ Waiting 30 seconds for deployment..."
          sleep 30

      - name: Verify deployment
        run: |
          echo "🔍 Checking server health..."
          for i in {1..10}; do
            if curl -f https://vibematch-arena.brad-dougherty.com/health; then
              echo "✅ Server is healthy!"
              exit 0
            fi
            echo "⏳ Attempt $i/10 - waiting..."
            sleep 5
          done
          echo "❌ Server health check failed"
          exit 1
